### ISSUE TITLE
i18n的ID也进行参数替换

### ISSUE THREAD

**Issue by 4tj** [gbk/i18n-helper#1]
现在传入key，如果有就根据传参替换，返回出value。如果key不存在（意味着该条语言没有定义），则返回传入的key。
此时key会将传入的参数原封不动的返回回来，应该做替换。

现在找不时：

```
i18n('{1}颗赛艇', '一');

{1}颗赛艇
```

期望：

```
i18n('{1}颗赛艇', '一');

一颗赛艇
```

**Comment by gbk** [comment]
merged
